export const enum SyllabicContext {
  MONO = 'MONO',

  FINAL = 'FINAL',

  NON_FINAL = 'NON_FINAL',

  PENULTIMATE = 'PENULTIMATE',

  ANTE_PENULTIMATE = 'ANTE_PENULTIMATE',

  ANTE_ANTE_PENULTIMATE = 'ANTE_ANTE_PENULTIMATE',
}
